name: publish release

on:
  workflow_dispatch: # Allow to manually trigger the pipeline
  release:
    types: [ published ]

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: zulu

      - name: Release version
        id: release
        run: echo "version=$(echo \"${{ github.ref }}\" | cut -d \"/\" -f3)" >> ${{ github.output }}

      - name: "Hello world"
        run: echo "${{ github.actor }}, ${{ secrets.GITHUB_TOKEN }}, ${{ github.ref }}, ${{ steps.release.outputs.version }}"

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker images
        run: ./gradlew -Pversion=${{ steps.release.outputs.version }} jar jibDockerBuild

      - name: Deploy to GH pages
        uses: ./.github/actions/mkdocs-publish
