name: publish release

on:
  workflow_dispatch: # Allow to manually trigger the pipeline
  release:
    types: [ published ]

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: zulu

      - name: Release version
        id: release
        run: echo "version=$(echo \"${GITHUB_REF}\" | cut -d \"/\" -f3)" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker images
        env:
          RELEASE_VER: ${{ steps.release.outputs.version }}
        run: ./gradlew jar jibDockerBuild

      - name: Deploy to GH pages
        uses: ./.github/actions/mkdocs-publish
