name: publish release

on:
  workflow_dispatch: # Allow to manually trigger the pipeline
  release:
    types: [ published ]

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: zulu

      - name: Release version
        id: release
        run: echo "version=$(echo ${{ github.ref }} | cut -d / -f3)" >> ${{ github.output }}

      - name: Setup Build
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./.github/scripts/setup-gradle.sh

      - name: Build and Push Docker images
        run: ./gradlew -Pversion=${{ steps.release.outputs.version }} jar jibDockerBuild

      - name: Deploy to GH pages
        uses: ./.github/actions/mkdocs-publish
